# Generated by Django 5.0.6 on 2024-11-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libros',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
