# Generated by Django 5.0.6 on 2024-11-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_perfilusuario_numero_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_membresia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
