# Generated by Django 5.0.6 on 2024-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfilusuario_numero_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_membresia',
            field=models.CharField(default='M', max_length=20),
        ),
    ]
